packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@prisma/engines": true
  esbuild: true
  prisma: true

catalog:
  "@eslint/js": 10.0.1
  "@next/eslint-plugin-next": 16.3.4
  "@prisma/adapter-pg": 7.10.0
  "@prisma/client": 7.10.0
  "@types/node": 26.4.1
  "@types/pg": 8.23.1
  "@types/react": 19.2.18
  "@types/react-dom": 19.2.7
  dotenv: 17.4.2
  eslint: 10.9.1
  eslint-config-prettier: 10.1.8
  eslint-plugin-react-hooks: 7.1.1
  eslint-plugin-turbo: 2.10.12
  eslint-plugin-unused-imports: 4.4.1
  globals: 17.12.0
  next: 16.3.4
  pg: 8.23.0
  prettier: 3.9.6
  prisma: 7.10.0
  react: 19.2.8
  react-dom: 19.2.8
  tsx: 4.23.13
  turbo: 2.10.12
  typescript: 6.0.3
  typescript-eslint: 8.69.0
  zod: 4.5.4
